version: "3.8"

services:
  app:
    build:
      dockerfile: docker/Dockerfile.dev
      context: ./inventory_management_pages
    image: inventory_app:dev
    container_name: inventory-app-pages
    # command: bash
    tty: true
    stdin_open: true
    restart: on-failure
    volumes:
      - ./inventory_management_pages:/app
    ports:
      - "8080:3000"
